Grossman. Algebra Lineal

$$2x_1 + 8x_2 + 6x_3 = 20$$
$$4x_1 + 2x_2 - 2x_3 = -2$$
$$3x_1 - x_2 + x_3 = 11$$

Esto se puede reescribir como: 
$$Ax=b$$
donde $A$ es la matriz de coeficientes y $b$ la matriz de resultados

In [5]:
A = [2 8 6; 4 2 -2; 3 -1 1]
b = [20; -2; 11]

3-element Vector{Int64}:
 20
 -2
 11

In [6]:
using LinearAlgebra

In [7]:
println("Determinante de A = ", det(A))
println("\nInversa de A = ", inv(A))
println("\nTranspuesta de A = ", transpose(A))
println("\nEigenvalores de A = ", eigen(A))

Determinante de A = -140.0

Inversa de A = [0.0 0.09999999999999998 0.2; 0.07142857142857142 0.11428571428571431 -0.2; 0.07142857142857142 -0.18571428571428572 0.2]

Transpuesta de A = [2 4 3; 8 2 -1; 6 -2 1]

Eigenvalores de A = Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}([-6.063759984475772, 2.7907650408333775, 8.272994943642399], [0.7781296635451158 0.28019317123558957 -0.8464834935771162; -0.4849824806207465 -0.5580873835248128 -0.4480841154321072; -0.39913183311045486 0.7810443387819747 -0.2875522919381905])


#### Matriz inversa

In [ ]:
A = [2 8 6; 4 2 -2; 3 -1 1]
b = [20; -2; 11]
x=inv(A)*b
println(x)

#### Regla de Cramer

In [8]:

A = [2 8 6; 4 2 -2; 3 -1 1]
b = [20; -2; 11]
DetA = det(A) # El determinante de A será usado para encontrar x1, x2, x3

# Obteniendo el valor de x1
Apivot = copy(A) # Para evitar que la matriz original se modifique, utilizamos copy
# Reemplazando la primera columna de la matriz de coeficientes (copia)
# por el vector de resultados
Apivot[:,1]= b
# Aplicando determinante a la matriz pivoteada
DetApivot = det(Apivot)
# Obteniendo el valor de x1
x1 = DetApivot/DetA

# Aplicando para x2 
Bpivot = copy(A)
DetB = det(Bpivot)
Bpivot[:,2] = b
DetBpivot = det(Bpivot)
x2 = DetBpivot/DetA

#Aplicando para x3
Cpivot = copy(A)
DetC = det(Cpivot)
Cpivot[:,3] = b
DetCpivot = det(Cpivot)
x3 = DetCpivot/DetA

println([x1, x2, x3])

[2.0, -1.0000000000000002, 4.0]


Aplicando de manera general

In [9]:
A = [2 8 6; 4 2 -2; 3 -1 1]
b = [20; -2; 11]
DetA = det(A)
xi = []

for i=1:3
    Apivot = copy(A)
    Apivot[:,i] = b
    DetApivot = det(Apivot)
    x = DetApivot/DetA
    append!(xi, x)
end
xi

3-element Vector{Any}:
  2.0
 -1.0000000000000002
  4.0

In [10]:
# Clase, elemento por elemento
A = [2 8 6; 4 2 -2; 3 -1 1]
b = [20; -2; 11]
DA = det(A)
xi = []
for i=1:3
    Ap = copy(A)
    for j=1:3 # Columna
        Ap[j, i] = b[j] # Matriz pivote
    end
    append!(xi, det(Ap)/DA)
end
xi

3-element Vector{Any}:
  2.0
 -1.0000000000000002
  4.0

#### Gauss simple

In [17]:
A = [3 -2 5 0; 4 5 8 1; 1 1 2 1; 2 7 6 5]
b = [2; 4; 5; 7]

function Gauss(A, b)
    Ap = float(copy(A)) # Copia flotante para evitar que realice cambios sobre el original
    bp = float(copy(b))
    n = length(b) # Tamaño de la matriz n x n
    x = zeros(n)
    # Proceso de eliminacion
    for k = 1:(n-1) # Indexacion del primer renglon con sus columnas
        for i = (k+1):n # Indexacion de filas restantes
            if Ap[i,k] == 0 # Si el elemento es cero, salta al siguiente
                continue
            end
            factor = Ap[k, k] / Ap[i, k] # factor utilizado para la eliminación de los valores de la columna
            for j = k:n # Indexacion de columnas restantes
                Ap[i, j] = Ap[k, j] - Ap[i, j]*factor # Criterio de eliminación
            end
            bp[i] = bp[k] - bp[i]*factor
        end
    end
    
    #=
    println("Matriz con ceros inferiores")
    println(Ap)
    println("\nVector de b")
    println(bp)
    =#

    # Sustitucion hacia atrás para encontrar los valores de x
    x[n] = bp[n] / Ap[n, n] # Solución de xn
    for i = n-1:-1:1 # Recorre la matriz desde el penultimo renglon hasta el primero
        sum_ax = 0.0 
        for j = i+1:n #  
            sum_ax = sum_ax + Ap[i, j]*x[j]
        end
        x[i] = (bp[i] - sum_ax)/Ap[i,i]
    end 
    #=
    println("\nSolucion de x[i]")
    println(x)
    =#
    return x
end

Gauss(A, b)

4-element Vector{Float64}:
  28.77777777777774
   2.166666666666663
 -15.999999999999977
   6.0555555555555545

#### Gauss con pivoteo parcial

In [18]:
A = [0 7 -1 3 1; 0 3 4 1 7; 6 2 0 2 -1; 2 1 2 0 2; 3 4 1 -2 1]
b = [5; 7; 2; 3; 4]

#=
A = [3 -2 5 0; 4 5 8 1; 1 1 2 1; 2 7 6 5]
b = [2; 4; 5; 7]
=#
function GaussPivoteoParcial(A, b)
    Ap = float(copy(A)) # Copia flotante para evitar que realice cambios sobre el original
    bp = float(copy(b))
    n = length(b) # Tamaño de la matriz n x n
    x = zeros(n)

    # Proceso de eliminacion
    for k = 1:(n-1) # Indexacion del primer renglon con sus columnas

        # Pivoteo parcial
        if abs(Ap[k, k]) < 1.0e-12 # Si el valor de elemento pivote es cero (practicamente)
            for i = (k+1):n # 
                if abs(Ap[i, k]) > abs(Ap[k, k]) # Si un elemento posterior al elemento pivote es mayor
                    for j = k:n 
                        Ap[k, j], Ap[i, j] = Ap[i, j], Ap[k, j] # Intercambio de elemento pivote Ap
                    end
                    bp[k], bp[i] = bp[i], bp[k] # Intercambio de elemento (correspondiente al renglon del pivote) bp
                    break # Regresa al ciclo anterior para continuar con la eliminacion
                end
            end
        end

        for i = (k+1):n # Indexacion de filas restantes
            if Ap[i,k] == 0 # Si el elemento es cero, salta al siguiente
                continue
            end
            factor = Ap[k, k] / Ap[i, k] # factor utilizado para la eliminación de los valores de la columna
            for j = k:n # Indexacion de columnas restantes
                Ap[i, j] = Ap[k, j] - Ap[i, j]*factor # Criterio de eliminación
            end
            bp[i] = bp[k] - bp[i]*factor
        end
    end

    # Sustitucion hacia atrás para encontrar los valores de x
    x[n] = bp[n] / Ap[n, n] # Solución de xn
    for i = n-1:-1:1 # Recorre la matriz desde el penultimo renglon hasta el primero
        sum_ax = 0.0 
        for j = i+1:n #  
            sum_ax = sum_ax + Ap[i, j]*x[j]
        end
        x[i] = (bp[i] - sum_ax)/Ap[i,i]
    end 
    #=
    println("\nSolucion de x[i]")
    println(x)
    =#
    return x
end

GaussPivoteoParcial(A, b)

5-element Vector{Float64}:
 0.030769230769230882
 0.7846153846153845
 1.015384615384615
 0.15384615384615374
 0.06153846153846176

#### Gauss - Jordan

In [21]:
A = [0 2 0 1; 2 2 3 2; 4 -3 0 1; 6 1 -6 -5]
b = [0; -2; -7; 6]

#=
A = [0 7 -1 3 1; 0 3 4 1 7; 6 2 0 2 -1; 2 1 2 0 2; 3 4 1 -2 1]
b = [5; 7; 2; 3; 4]
=#

#=
A = [3 -2 5 0; 4 5 8 1; 1 1 2 1; 2 7 6 5]
b = [2; 4; 5; 7]
=#
function GaussJordan(A, b)
    Ap = float(copy(A)) # Copia flotante para evitar que realice cambios sobre el original
    bp = float(copy(b))
    n = length(b) # Tamaño de la matriz n x n
    for k = 1:n # Indexacion del primer renglon con sus columnas

        # Pivoteo parcial
        if abs(Ap[k, k]) < 1.0e-12 # Si el valor de elemento pivote es cero (practicamente)
            for i = (k+1):n # 
                if abs(Ap[i, k]) > abs(Ap[k, k]) # Si un elemento posterior al elemento pivote es mayor
                    for j = k:n 
                        Ap[k, j], Ap[i, j] = Ap[i, j], Ap[k, j] # Intercambio de elemento pivote Ap
                    end
                    bp[k], bp[i] = bp[i], bp[k] # Intercambio de elemento (correspondiente al renglon del pivote) bp
                    break # Regresa al ciclo anterior para continuar con la eliminacion
                end
            end
        end

        # Division de la fila pivote
        pivote = Ap[k, k]
        for j = k:n
            Ap[k, j] = Ap[k, j] / pivote
        end
        bp[k] = bp[k] / pivote 

        # Proceso de eliminacion
        for i = 1:n
            if i == k || Ap[i, k] == 0
                continue
            end 
            factor = Ap[i, k]
            for j = k:n
                Ap[i, j] = Ap[i, j] - Ap[k, j]*factor
            end
            bp[i] = bp[i] - bp[k]*factor
        end
    end
    #=
    println("Matriz identidad")
    println(Ap)
    println("Solucion x[i]")
    println(bp)
    =#
    return bp
end

GaussJordan(A, b)

4-element Vector{Float64}:
 -0.5
  1.0
  0.33333333333333337
 -2.0